### ISSUE TITLE
login to wm failed

### ISSUE THREAD

**Issue by jakubovciak** [chipster/chipster#46]
I have a problem logging into latest version of chipster WM in Virtualbox. Credentials username "ubuntu" and pwd "chipster" don't work. Chipster local server runs normally though. Not an issue in version 3.8.1., everything works fine there.

**Comment by klemela** [comment]
The credentials are correct. Have you perhaps downloaded the Chipster-cloud.ova image, where the password login is completely disabled? Using the regular Chipster.ova image should help in this case.

If you have more questions, please send them to chipster-tech@lists.sourceforge.net so that all questions and answers can be found in one place.
